# Generated by Django 3.2.9 on 2021-12-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0005_auto_20190710_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='windenergysite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
