# Generated by Django 2.2.10 on 2020-02-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0003_auto_20170706_1438'),
        ('drawing', '0005_auto_20190710_2310'),
    ]

    operations = [
    ]
