# Generated by Django 3.2.16 on 2024-03-06 23:02

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0006_auto_20211216_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#EE9900', image_field=None, max_length=18, null=True, samples=[('#FFFFFF', 'white'), ('#888888', 'gray'), ('#000000', 'black'), ('#FF0000', 'red'), ('#FFFF00', 'yellow'), ('#00FF00', 'green'), ('#00FFFF', 'cyan'), ('#0000FF', 'blue'), ('#FF00FF', 'magenta')], verbose_name='Fill Color'),
        ),
        migrations.AddField(
            model_name='aoi',
            name='fill_opacity',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='aoi',
            name='stroke_color',
            field=colorfield.fields.ColorField(blank=True, default='#EE9900', image_field=None, max_length=18, null=True, samples=[('#FFFFFF', 'white'), ('#888888', 'gray'), ('#000000', 'black'), ('#FF0000', 'red'), ('#FFFF00', 'yellow'), ('#00FF00', 'green'), ('#00FFFF', 'cyan'), ('#0000FF', 'blue'), ('#FF00FF', 'magenta')], verbose_name='Stroke Color'),
        ),
        migrations.AddField(
            model_name='aoi',
            name='stroke_width',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Stroke Width'),
        ),
    ]
