# Generated by Django 4.2 on 2024-04-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0007_alter_aoi_content_type_alter_aoi_sharing_groups_and_more'),
        ('drawing', '0007_auto_20240306_2302'),
    ]

    operations = [
    ]
