# Generated by Django 4.2.20 on 2025-04-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0008_auto_20250425_2139'),
        ('drawing', '0009_alter_aoi_color_alter_aoi_stroke_color'),
    ]

    operations = [
    ]
