SHARING_TO_PUBLIC_GROUPS=['Share with Public']
SHARING_TO_STAFF_GROUPS=['Share with staff']

KML_SIMPLIFY_TOLERANCE = 20 #meters
KML_SIMPLIFY_TOLERANCE_DEGREES = 0.0002 # very roughly ~ 20 meters
KML_EXTRUDER_HEIGHT = 100
KML_ALTITUDEMODE_DEFAULT = 'absolute'
